name: Render and Publish

# Only run this when the main branch changes
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Allow manual triggering from the UI
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    concurrency:
      group: "pages"
      cancel-in-progress: false
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE
      
      # Install R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      # Install R dependencies
      - name: Install R Dependencies 
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          
      # Alternative: install specific packages if no renv.lock file
      - name: Install packages
        run: |
          if (!requireNamespace("rmarkdown", quietly = TRUE)) install.packages("rmarkdown")
          if (!requireNamespace("readr", quietly = TRUE)) install.packages("readr")
          if (!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")
          if (!requireNamespace("ggplot2", quietly = TRUE)) install.packages("ggplot2")
          if (!requireNamespace("knitr", quietly = TRUE)) install.packages("knitr")
        shell: Rscript {0}

      # Render the project
      - name: Render Quarto Project
        run: |
          quarto render
          
      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2